NOAA-EMC/UFS_UTILS

ush/fv3gfs_chgres.sh
Merge minor change to `fv3gfs_chgres.sh` script from 'release/v1.1.0' to head of 'develop'.
=> release/v1.1.0:  This commit references #26.

reg_tests/chgres_cube/driver.jet.sh, sorc/chgres_cube.fd/surface.F90
Fix to `chgres_cube` to eliminate non-zero snow over open water and non-zero ice depth at ice-free points.  See #27 of more details.
=> chgres_cube snow fix

CMakeLists.txt
- update OpenMP logic: by default, OpenMP is off
- update submodule pointer for cmake
=> Bugfix for OpenMP

sorc/chgres_cube.fd/input_data.F90, sorc/chgres_cube.fd/program_setup.f90, sorc/chgres_cube.fd/write_data.F90
=> Fix error_handler call statements. Last argument (rc) must be present.

docs/CHGRES_CUBE.rst
Add Valbona's latest update to docs/CHGRES_CUBE.rst.
=> Update CHGRES_CUBE.rst in release/public-v1

LICENSE.md
Update license for ufs_utils public release.
=> Update license for public release branch

reg_tests/global_cycle/C768.fv3gfs.sh, reg_tests/global_cycle/driver.cray.sh, reg_tests/global_cycle/driver.dell.sh, reg_tests/global_cycle/driver.hera.sh, reg_tests/global_cycle/driver.jet.sh, reg_tests/grid_gen/c96.regional.sh, reg_tests/grid_gen/c96.uniform.sh, reg_tests/grid_gen/driver.cray.sh, reg_tests/grid_gen/driver.dell.sh, reg_tests/grid_gen/driver.hera.sh, reg_tests/grid_gen/driver.jet.sh, reg_tests/ice_blend/driver.cray.sh, reg_tests/ice_blend/driver.dell.sh, reg_tests/ice_blend/driver.hera.sh, reg_tests/ice_blend/driver.jet.sh, reg_tests/ice_blend/ice_blend.sh, reg_tests/snow2mdl/driver.cray.sh, reg_tests/snow2mdl/driver.dell.sh, reg_tests/snow2mdl/driver.hera.sh, reg_tests/snow2mdl/driver.jet.sh, reg_tests/snow2mdl/snow2mdl.sh
New regression tests for `global_cycle`, `emcsfc_ice_blend`, `emcsfc_snow2mdl` and all programs
associated with the grid generation.
=> Regression tests for global_cycle, emcsfc and grid programs.

driver_scripts/driver_grid.jet.sh, fix/link_fixdirs.sh, modulefiles/build.jet, modulefiles/module-setup.sh.inc, modulefiles/module_base.jet, reg_tests/chgres_cube/driver.jet.sh, reg_tests/global_cycle/driver.jet.sh, reg_tests/grid_gen/driver.jet.sh, reg_tests/ice_blend/driver.jet.sh, reg_tests/snow2mdl/driver.jet.sh
On June 1, the directory 'project' was changed to 'HFIP'.  And on June 30, the /lfs3 disk will be replaced by /lfs4.  Repository was updated accordingly.   For details, see #107.
=> Update for path changes on Jet

modulefiles/chgres_cube.wcoss_cray
Simple change to get away from pointing at a George Gayno directory for the needed wgrib2 build items.
=> Attempt to update chgres_cube.wcoss_cray in my fork

driver_scripts/driver_grid.jet.sh, driver_scripts/driver_grid.orion.sh, modulefiles/chgres_cube.jet, modulefiles/chgres_cube.orion, modulefiles/fv3gfs/fre-nctools.orion, modulefiles/fv3gfs/global_chgres.orion, modulefiles/fv3gfs/global_cycle.orion, modulefiles/fv3gfs/nst_tf_chg.orion, modulefiles/fv3gfs/orog.orion, modulefiles/module_nemsutil.jet, modulefiles/module_nemsutil.orion, modulefiles/modulefile.global_emcsfc_ice_blend.orion, modulefiles/modulefile.global_emcsfc_snow2mdl.orion, modulefiles/modulefile.sfc_climo_gen.jet, modulefiles/modulefile.sfc_climo_gen.orion, reg_tests/chgres_cube/driver.jet.sh, sorc/build_orog.sh, sorc/fre-nctools.fd/tools/filter_topo/make.csh_orion, sorc/fre-nctools.fd/tools/fregrid/env.orion, sorc/fre-nctools.fd/tools/fregrid/fre-nctools.mk_orion, sorc/fre-nctools.fd/tools/make_hgrid/env.orion, sorc/fre-nctools.fd/tools/make_hgrid/fre-nctools.mk_orion, sorc/fre-nctools.fd/tools/make_solo_mosaic/env.orion, sorc/fre-nctools.fd/tools/make_solo_mosaic/fre-nctools.mk_orion, sorc/fre-nctools.fd/tools/shave.fd/build_shave, sorc/global_chgres.fd/chgres_utils.f90, sorc/link_fixdirs.sh, sorc/machine-setup.sh
Port the release branch to Orion.
Update branch for recent sys admin directed changes on Jet.
See #26 for details.
=> Update GFS v16 release branch for Orion and Jet

docs/source/chgres_cube.rst
Update the 'chgres_cube.rst' file to match MRW App v1.1.0
Issue #175.
=> Update the 'chgres_cube.rst' file to match MRW App v1.1.0

sorc/sfc_climo_gen.fd/driver.F90, sorc/sfc_climo_gen.fd/interp.F90, sorc/sfc_climo_gen.fd/model_grid.F90, sorc/sfc_climo_gen.fd/output.f90, sorc/sfc_climo_gen.fd/program_setup.f90, sorc/sfc_climo_gen.fd/search.f90, sorc/sfc_climo_gen.fd/source_grid.F90, sorc/sfc_climo_gen.fd/utils.f90, sorc/vcoord_gen.fd/driver.f90, sorc/vcoord_gen.fd/matrix_utils.f90, sorc/vcoord_gen.fd/vcoord_gen.f90
Part of #191 
More work on the doxygen documentation.
=> More doxygen work

docs/source/chgres_cube.rst
Update the chgres_cube.rst documentation file to match the version in 'develop' and the MRW App v1.1.
Issue #175.
=> Update the chgres_cube.rst documentation

CMakeLists.txt, docs/CMakeLists.txt, docs/Doxyfile.in, docs/user_guide.md, sorc/nst_tf_chg.fd/nc_check.f90, sorc/nst_tf_chg.fd/read_tfs_nc.f90, sorc/nst_tf_chg.fd/read_tfs_nc_2d.f90, sorc/nst_tf_chg.fd/setup.f90, sorc/nst_tf_chg.fd/smth9_msk.f90, sorc/orog_mask_tools.fd/inland.fd/inland.F90, sorc/orog_mask_tools.fd/inland.fd/nb.F90, sorc/orog_mask_tools.fd/lake.fd/enclosure_cnvx.F90, sorc/orog_mask_tools.fd/lake.fd/find_limit.F90, sorc/orog_mask_tools.fd/lake.fd/lakefrac.F90, sorc/orog_mask_tools.fd/orog.fd/mtnlm7_oclsm.f, sorc/orog_mask_tools.fd/orog.fd/netcdf_io.F90
Part of #191 
More doxygen changes.
=> more doxygen changes

.github/workflows/build_and_test.yml
Automatically builds UFS_UTILS on every push and commit. No code changes.
=> Create workflow for UFS_UTILS

docs/source/chgres_cube_regional.rst, sorc/chgres_cube.fd/atmosphere.F90, sorc/chgres_cube.fd/input_data.F90, sorc/chgres_cube.fd/model_grid.F90, sorc/chgres_cube.fd/program_setup.f90
This PR addresses all of the listed items in Issue #228. Code compiles and passes all current and future regression tests on Jet.
=> release/public-v2: Various chgres_cube bug fixes and code improvements

sorc/chgres_cube.fd/atmosphere.F90, sorc/chgres_cube.fd/input_data.F90, sorc/chgres_cube.fd/model_grid.F90, sorc/chgres_cube.fd/program_setup.f90
This PR addresses all of the items listed in Issue #228 . Each item in that issue is addressed with its own commit.
=> develop: Various chgres_cube bug fixes and code improvements

sorc/chgres_cube.fd/input_data.F90, sorc/chgres_cube.fd/search_util.f90, sorc/chgres_cube.fd/surface.F90
chgres_cube fix for soil type == 0 at land ice points when using soil and vegetation type from input data.
Addresses Issue #246.
=> Soil type at land ice fix when using soil and vegetation type from input data (HRRR/RAP)

sorc/chgres_cube.fd/model_grid.F90
=> doxygen for model_grid.F90

tests/chres_cube/CMakeLists.txt, tests/chres_cube/config.nml, tests/chres_cube/ftst_program_setup.F90
Part of #280 
This is a test for the namelist read subroutine. More program_setup testing will follow in future PRs.
=> Start of testing for program_setup.F90

README.md
=> updated readme with readthedocs documentation for chgres_cube

sorc/chgres_cube.fd/chgres.F90, sorc/chgres_cube.fd/input_data.F90, sorc/chgres_cube.fd/program_setup.f90, sorc/chgres_cube.fd/search_util.f90, sorc/chgres_cube.fd/surface.F90
More doxygen for chgres_cube.
@GeorgeGayno-NOAA please check out this branch and fill in the missing doxygen for public variables.
Part of #191 
Fixes #327
=> More chgres_cube doxygen

sorc/emcsfc_snow2mdl.fd/grib_utils.f
Fixes #291 
Part of #191 
fix doxygen for sorc/emcsfc_snow2mdl.fd/grib_utils.f
=> fix doxygen for sorc/emcsfc_snow2mdl.fd/grib_utils.f

sorc/chgres_cube.fd/surface.F90
Minor doxygen updates.
Fixes #281
=> Doxygen updates to chgres_cube.fd/surface.F90

sorc/chgres_cube.fd/atmosphere.F90, sorc/chgres_cube.fd/grib2_util.F90, sorc/chgres_cube.fd/input_data.F90, sorc/chgres_cube.fd/model_grid.F90, sorc/chgres_cube.fd/program_setup.F90, sorc/chgres_cube.fd/search_util.F90, sorc/chgres_cube.fd/static_data.F90, sorc/chgres_cube.fd/surface.F90, sorc/chgres_cube.fd/thompson_mp_climo_data.F90, sorc/chgres_cube.fd/utils.F90
Part of #191 
Part of #357 
Fixing doxygen handling of modules in chgres_cube.
=> improving module documentation in chgres_cube

sorc/grid_tools.fd/shave.fd/shave_nc.F90
PR for shave_nc.F90 doxygen
Part of #366
=> Doxygen improvements for sorc/grid_tools.fd/shave.fd/shave_nc.F90

sorc/grid_tools.fd/regional_esg_grid.fd/psym2.f90
Doxygen update for regional_esg_grid.fd/psym2.f90
Part of #366
=> Doxygen improvements for sorc/grid_tools.fd/regional_esg_grid.fd/psym2.f90

sorc/emcsfc_ice_blend.fd/emcsfc_ice_blend.f90
fixes #342 
Doxygen warning fixes for sorc/emcsfc_ice_blend.fd
=> fixed doxygen warnings in sorc/emcsfc_ice_blend.fd

sorc/grid_tools.fd/regional_esg_grid.fd/pesg.f90, sorc/grid_tools.fd/regional_esg_grid.fd/pfun.f90, sorc/grid_tools.fd/regional_esg_grid.fd/pkind.f90, sorc/grid_tools.fd/regional_esg_grid.fd/pmat2.f90
part of #343
more doxygen fixes for sorc/grid_tools.fd files: pmat2.f90, pesg.f90, pfun.f90, pkind.f90
=> more doxygen fixes for sorc/grid_tools.fd files: pmat2.f90, pesg.f90, pfun.f90, pkind.f90

sorc/emcsfc_snow2mdl.fd/driver.f, sorc/emcsfc_snow2mdl.fd/grib_utils.f, sorc/emcsfc_snow2mdl.fd/model_grid.f, sorc/emcsfc_snow2mdl.fd/program_setup.f, sorc/emcsfc_snow2mdl.fd/snow2mdl.f, sorc/emcsfc_snow2mdl.fd/snowdat.f
Part of #191 
Fixes #291 
@GeorgeGayno-NOAA there's some ??? to be filled in for these codes.
=> fix rest of doxygen warnings for emcsfc_snow2mdl.fd

sorc/grid_tools.fd/regional_esg_grid.fd/pesg.f90
I have asked the author to contribute some info. This PR is to highlight the missing fields we need filled in.
Part of #191 
Part of #343 
@JimPurser-NOAA this is for you. ;-)
=> highlighted doxygen questions for R. J. Purser in sorc/grid_tools.fd/regional_esg_grid.fd code

docs/Doxyfile.in, docs/user_guide.md, sorc/sfc_climo_gen.fd/docs/Doxyfile.in, sorc/sfc_climo_gen.fd/driver.F90, sorc/sfc_climo_gen.fd/interp.F90, sorc/sfc_climo_gen.fd/model_grid.F90, sorc/sfc_climo_gen.fd/output.f90, sorc/sfc_climo_gen.fd/program_setup.f90, sorc/sfc_climo_gen.fd/search.f90, sorc/sfc_climo_gen.fd/source_grid.F90, sorc/sfc_climo_gen.fd/utils.f90
Part of #191.
Fixes #401 
Fixing doxygen warnings for sfc_climo_gen.
=> clearing doxygen warnings for sfc_climo_gen

sorc/orog_mask_tools.fd/inland.fd/inland.F90
=> Fix doxygen warnings in ./inland.fd/inland.F90

sorc/grid_tools.fd/regional_esg_grid.fd/pfun.f90, sorc/grid_tools.fd/regional_esg_grid.fd/pkind.f90
Part of #191 
Part of #343 
More documentation filled in by R. Purser.
=> doxygen updates in sorc/grid_tools.fd - applied comments from R. Purser

sorc/global_cycle.fd/machine.f90, sorc/global_cycle.fd/sfcsub.F
Add doxygen to the remaining routines in the sfcsub.F.  Also define all variables in its sfccyc_module.  Add doxygen to machine.f90 and remove unused variables.
Part of #191 
Fixes #398
Fixes #412
=> Doxygen updates to global_cycle

sorc/chgres_cube.fd/atmosphere.F90, sorc/chgres_cube.fd/chgres.F90, sorc/chgres_cube.fd/docs/user_guide.md, sorc/chgres_cube.fd/grib2_util.F90, sorc/chgres_cube.fd/input_data.F90, sorc/chgres_cube.fd/model_grid.F90, sorc/chgres_cube.fd/search_util.F90, sorc/chgres_cube.fd/static_data.F90, sorc/chgres_cube.fd/surface.F90, sorc/chgres_cube.fd/write_data.F90, sorc/emcsfc_ice_blend.fd/docs/user_guide.md, sorc/emcsfc_snow2mdl.fd/docs/user_guide.md, sorc/fvcom_tools.fd/docs/user_guide.md, sorc/global_cycle.fd/docs/user_guide.md, sorc/grid_tools.fd/docs/user_guide.md, sorc/orog_mask_tools.fd/docs/user_guide.md, sorc/sfc_climo_gen.fd/docs/user_guide.md, sorc/vcoord_gen.fd/docs/user_guide.md
Part of #191 
Improving the doxygen docs.
In this PR I improve the user_guide of the chgres_cube utility, and also add a little formatting to the other users guides.
=> improved chgres_cube doxygen docs with info from chgres_cube.rst, added some formatting in other utility user guides

sorc/global_cycle.fd/docs/Doxyfile.in
Part of #191 
Part of #398 
Turn on WARN_AS_ERROR for global_cycle.
=> turn on WARN_AS_ERROR for global_cycle

.github/workflows/esmf-8.0.1_jasper-2.0.22_nceplibs-develop.yml
=> Use --html-details option in gcovr and upload all html files

README.md, sorc/chgres_cube.fd/docs/user_guide.md, sorc/emcsfc_ice_blend.fd/docs/user_guide.md, sorc/emcsfc_snow2mdl.fd/docs/user_guide.md, sorc/emcsfc_snow2mdl.fd/driver.F90, sorc/fvcom_tools.fd/docs/user_guide.md, sorc/global_cycle.fd/docs/user_guide.md, sorc/grid_tools.fd/docs/user_guide.md, sorc/grid_tools.fd/regional_esg_grid.fd/pmat2.f90, sorc/orog_mask_tools.fd/docs/user_guide.md, sorc/orog_mask_tools.fd/orog.fd/mtnlm7_oclsm.f, sorc/sfc_climo_gen.fd/docs/user_guide.md, sorc/vcoord_gen.fd/docs/user_guide.md, sorc/vcoord_gen.fd/driver.f90
Part of #191 
Landing page cleanup, also add link to the programs on the landing page, so their documentation can be found easily.
=> Cleanup the landing page of each utility's documentation

sorc/orog_mask_tools.fd/inland.fd/CMakeLists.txt, sorc/orog_mask_tools.fd/lake.fd/CMakeLists.txt
=> Fix install of lakefrac and inland

tests/chgres_cube/ftst_search_util.F90
Name all parameters.
Check all values returned from search routine.
Remove print statements for errors.
#498
=> Improve chgres_cube test ftst_search_util.F90

.github/workflows/debug-docs-test_coverage.yml, .github/workflows/intel.yml, .github/workflows/linux-mac-nceplibs-mpi.yml, .github/workflows/netcdf-versions.yml, tests/chgres_cube/CMakeLists.txt, tests/chgres_cube/data/files.txt, tests/chgres_cube/ftst_read_sfc_netcdf.F90
New test for routine "read_input_sfc_netcdf_file". Read a reduced-in-size
GFS v16 NetCDF history file and check each surface record against
known values.
Fixes #510
=> Unit test for chgres_cube/read_input_sfc_netcdf_file

tests/chgres_cube/CMakeLists.txt, tests/chgres_cube/data/files.txt, tests/chgres_cube/ftst_read_atm_gaussian_netcdf.F90, tests/chgres_cube/ftst_read_atm_netcdf.F90
Test reads a reduced-in-size GFS v16 atmospheric NetCDF history
file. Data values read from the routine are compared against 
expected values.
Fixes #513 
Part of #256
=> Unit test for chgres_cube.fd/read_input_atm_gaussian_netcdf_file routine

util/gdas_init/get_v16retro.data.sh
The location of NCO's GFS v16 real-time parallel was moved on HPSS. Update the GDAS_INIT utility
accordingly. 
#558
=> GDAS_INIT utility - point to correct v16 retro GFS HPSS directory

modulefiles/build.jet.intel, util/gdas_init/config, util/gdas_init/driver.jet.sh
Port the utility to support the global_workflow group.
Fixes #544
=> Port the GDAS_INIT utility to Jet
