NOAA-EMC/UFS_UTILS

driver_scripts/driver_grid.jet.sh
modulefiles/chgres_cube.jet
modulefiles/fv3gfs/global_chgres.jet
modulefiles/fv3gfs/global_cycle.jet
modulefiles/fv3gfs/nst_tf_chg.jet
modulefiles/fv3gfs/orog.jet
modulefiles/module_base.jet
modulefiles/module_nemsutil.jet
modulefiles/modulefile.global_emcsfc_ice_blend.jet
modulefiles/modulefile.global_emcsfc_snow2mdl.jet
modulefiles/modulefile.sfc_climo_gen.jet
reg_tests/chgres_cube/driver.jet.sh
sorc/machine-setup.sh
ush/fv3gfs_driver_grid.sh

NCEPLIBS was recompiled and moved on Jet.  Update repository so it compiles and runs.  See issue #34 for more details.

Update for new NCEPLIB library location on Jet

---

reg_tests/chgres_cube/driver.cray.sh
reg_tests/chgres_cube/driver.dell.sh
sorc/chgres_cube.fd/input_data.F90

Zero out vertical velocity when using tiled history and tiled warm restart data as input to chgres_cube.  For details, see issue #31

chgres_cube vertical velocity fix

---

CMakeLists.txt

This PR adds a guard inCMakeLists.txt to prevent building UFS_UTILS using cmake standalone. This has not been implemented yet, because we are now using the findESMF macro directly from ESMF. Using this macro requires a bit of additional logic (see NCEPLIBS umbrella build CMakeLists.txt, branhf ufs_release_v1.0).
This PR also adds support for macOS with clang compilers, which somehow slipped in previous PRs. I am going to merge this PR, because it doesn't remove/change any working logic.
Note: the following CMakeLists.txt files only know about the Intel compiler and return an "unknown compiler" warning for any other compiler. This needs to be fixed (see issue https://github.com/NOAA-EMC/UFS_UTILS/issues/44).

Catch unimplemented build method, add support for macOS compilers

---

modulefiles/fv3gfs/global_chgres.hera
modulefiles/fv3gfs/global_chgres.wcoss_dell_p3
modulefiles/fv3gfs/global_cycle.hera
modulefiles/fv3gfs/global_cycle.wcoss_dell_p3
modulefiles/module_base.hera
modulefiles/module_base.wcoss_dell_p3
sorc/global_chgres.fd/chgres.f90

Fanglin requested a switch to these libraries to support GFS v16 (Hera/Dell):
hdf5_parallel/1.10.6 and netcdf_parallel/4.7.4
Only the old serial chgres and global_cycle programs are used by the global workflow.
Hence, no other programs were updated.   
Also, fix an out-of-bounds array in serial chgres discovered by Dusan.

Update serial chgres and cycle to use parallel netcdf 4.7.4

---

reg_tests/chgres_cube/c192.fv3.history.sh
reg_tests/chgres_cube/c192.gfs.grib2.sh
reg_tests/chgres_cube/driver.cray.sh
reg_tests/chgres_cube/driver.dell.sh
reg_tests/chgres_cube/driver.hera.sh
reg_tests/chgres_cube/driver.jet.sh
sorc/chgres_cube.fd/write_data.F90
ush/chgres_cube.sh

CHGRES_CUBE was recently updated to ingest GFS GRIB2 data.  Add a regression test for this new capability.  
Fix legacy Fortran extension in routine "write_data.F90" identified by Dusan.

Add GRIB2 regression test for CHGRES_CUBE

---

LICENSE.md

NOAA legal approved licenses for our component repositories.  For EMC components
we are using the LGPL.

Add LGPL license to repository.

---

CMakeLists.txt

The CMake build doesn't use `landsfcutil` for anything, so we shouldn't look for it

Remove find_package(landsfcutil) because it is not used

---

sorc/chgres_cube.fd/write_data.F90
sorc/orog.fd/netcdf_io.F90
sorc/sfc_climo_gen.fd/interp.F90
sorc/sfc_climo_gen.fd/model_grid.F90
sorc/sfc_climo_gen.fd/output.f90

Add geo-referencing to the files output by the orography maker, the sfc_climo_gen program, and chgres_cube.  Remove lat/lon records from the orography files, which are not used and can contain bad values.  See issues #11 and #22.

Add geo-referencing to 'oro', 'sfc_climo' and 'coldstart' files

---

modulefiles/build.hera
modulefiles/build.wcoss_cray
modulefiles/build.wcoss_dell_p3

The NDATE program was not being defined in the GDAS initialization scripts.
As a result, the scripts would not work when initializing with GFS v15 data.
For details see #115.

Define NDATE in GDAS initialization scripts

---

.gitmodules

Point to develop of the CMakeModules authoritative repo.
Previously, I was inadvertently pointing to my fork.
See #122 for more details.

Update CMakeModules pointer

---

docs/source/chgres_cube.rst

This is a minimal update of the documentation on how to compile UFS_UTILS standalone. We will need to update the ufs-v1.1.0 tags of UFS_UTILS and NCEPLIBS umbrella after this PR is merged.

release/public-v1: update instructions to compile UFS_UTILS standalone

---

modulefiles/build.hera

NCEPLIBS was built with a different NetCDF and it wasn't updated in this modulefile. @JeffBeck-NOAA found he couldn't run the wgrib2 executable with this NetCDF loaded.
I ran regression tests on Hera and they all passed.

Update NetCDF and HDF5 modules on Hera

---

sorc/fre-nctools.fd/tools/make_solo_mosaic/make_solo_mosaic.c

Change the length of the string mosaic_name in make_solo_mosaic.c from just 128 characters to STRING=255 characters.
This is needed because the way make_solo_mosaic is called in regional_workflow, mosaic_name includes not only the basename of the mosaic file but also the absolute path to it, and that path can get longer than 128 characters.  In that case, make_solo_mosaic fails (without a clear error message).  It would be even better to make mosaic_name a variable length string, but I don't remember how to do that in c.  This suffices for now.
I tested this with ~25 different tests in regional_workflow with varying mosaic_name lengths, and they all passed (whereas some of them failed previously with only a 128 character mosaic_name).

Make size of mosaic_name string in make_solo_mosaic longer

---

sorc/chgres_cube.fd/model_grid.F90
sorc/chgres_cube.fd/utils.f90
sorc/sfc_climo_gen.fd/interp.F90
sorc/sfc_climo_gen.fd/model_grid.F90

This PR is an attempt to fox the grib2 read errors encountered with large task counts randomly on several machines. The issue is described in length in https://github.com/ufs-community/ufs-mrweather-app/issues/190, together with a suggestion from @GeorgeGayno-NOAA in https://github.com/ufs-community/ufs-mrweather-app/issues/190#issuecomment-696946981 (implemented here).
Changes in this PR:
- sorc/chgres_cube.fd/model_grid.F90: read grib2 inventory only with task 0, let all other processes wait for it to complete
- correct syntax for `MPI_ABORT` calls in various files (from @DusanJovic-NOAA)
Testing:
- Installed a new/test version of NCEPLIBS ufs-v1.1.0 that contains this bugfix on orion and ran the full MRW App regression tests, all of them passed.
- Due to the random nature of the error, …

release/public-v1: attempt to fix grib2 read errors with large task counts (draft PR)

---

util/gdas_init/driver.hera.sh
util/gdas_init/run_pre-v14.chgres.sh
util/gdas_init/run_v14.chgres.sh
util/gdas_init/run_v15.chgres.sh

Update the GDAS initialization utility for the new 'atmos' subdirectory employed by the global workflow.  Add load of NDATE utility in the hera driver script, which was inadvertently removed during a previous commit.
See issue #159 for more details.

Update GDAS initialization utility for ATMOS subdirectory

---

sorc/emcsfc_snow2mdl.fd/CMakeLists.txt
sorc/emcsfc_snow2mdl.fd/snow2mdl.f

The snow2mdl program uses two small routines from the landsfcutil library.  Incorporate these routines into snow2mdl, thereby removing its dependency on the library.
For details, see issue #169

Remove landsfcutil library dependency from snow2mdl program

---

sorc/chgres_cube.fd/program_setup.f90

The return statement in read_setup_namelist is a few lines too early, and before the if statement that sets use_thomp_mp_climo to true if thomp_mp_climo_file is set in the namelist. This prevents the aerosols from ever being created or written to file, regardless of input data type. Addresses issue https://github.com/NOAA-EMC/UFS_UTILS/issues/178

Fix bug that prevents Thompson aerosols from being created

---

README.md
docs/Doxyfile.in
sorc/nst_tf_chg.fd/nst_tf_chg.f90

Part of #191 
I have built the current doxygen docs, and put them up at https://noaa-emc.github.io/UFS_UTILS/. I will update as we develop these docs. Eventually, this on-line version will only be updated when we do a version release, but while the docs are under development, I will keep it updated when there are changes.
In this PR I add the list of source directories to the Doxyfile.in. If directories are added, renamed, or deleted, the Doxyfile.in will also need to be updated so it can find the code.
In our code, we must convert existing comments to doxygen comments. I have done so for one file in this PR.
Once we get this PR merged I will convert the other Fortran files, in batches, trying to avoid any active work areas so there are no conflicts.

more doxygen work

---

modulefiles/build.jet

The NCEPLIBS build directory on Jet changed recently and requires an update to the module file.
Resolves Issue #204.

Change NCEPLIBS directory in the Jet module file

---

modulefiles/build.jet.intel

On Jet, UFS_UTILS was pointing to Dom's directory, which was recently moved/renamed.  As a result, the repo can't be compiled on Jet - an officially supported machine.
For more details see #196.

Point to new NCEPLIBS location on Jet

---

modulefiles/build.wcoss_cray

Is a temporary change, but right now chgres_cube won't build with the existing module file.  I'm planning to deliver to NCO early next week, so would like to give them something that will build out of the box.

Changes from nwprod to nwpara for wgrib2 v2.0.8 library

---

sorc/chgres_cube.fd/input_data.F90

Some isobaric files have data on some hybrid levels. This addresses waves on boundaries when using operational RAP data for LBCs.
Addresses Issue #222

wgrib2 text search fix to account for isobaric files 

---

sorc/orog_mask_tools.fd/orog.fd/mtnlm7_oclsm.f

There are some declarations of allocatable variables that result in `illegal instruction` errors on MacOS, despite being valid Fortran77 code. One such instance is found in `sorc/orog_mask_tools.fd/orog.fd/mtnlm7_oclsm.f`, where the real `hgt_1d` is declared in the subroutine MAKEMT2. While the existing code is valid, it can be rearranged in a way that does not trigger this error but gives equivalent results.
This code has been tested on MacOS (GNU 9.3.0), Cheyenne (GNU 10.1.0) and Hera (Intel 18.0.5) by running the end-to-end UFS SRW App workflow release branch tests. Also checked on Cheyenne to ensure the output files from `orog` for the GST test case were bit-for-bit identical. Let me know if there are any other tests required for this PR to be accepted.
This PR will resolve Issue …

Rearrange allocation of hgt_1d in mtnlm7_oclsm.f to fix errors on MacOS

---

.github/workflows/build_and_test.yml

Fifth time's the charm!
Part of #260 
It took me many tries to get the right. Turns out that GitHub actions sometimes just freezes when your workflow file is wrong. ;-)
In this PR I change the CI to get ESMF and other codes with wget, instead of checking them out, and then I use GitHub caching, so that these codes are only build the first time. For subsequent tests, GitHub pulls them from the cache.

updated workflow to enable caching of ESMF

---

.github/workflows/build_and_test.yml
.github/workflows/esmf-8.0.1_jasper-2.0.22_nceplibs-1.3.0.yml
.github/workflows/esmf-8.0.1_jasper-2.0.22_nceplibs-develop.yml

Fixes #260 
Fixes #259
Now cache jasper build.
Also rename workflows for clarity.
Also added workflow to test against nceplibs-1.3.0.
Changed existing workflow to use nceplibs develop branch.

for GitHub workflow,s, use caching, rename for clarity, add workflow for nceplibs develop branch test

---

sorc/chgres_cube.fd/grib2_util.F90
sorc/chgres_cube.fd/input_data.F90
sorc/chgres_cube.fd/utils.F90
tests/chres_cube/ftst_utils.F90

One version was a function and the other was a subroutine.  Only the function was being used by chgres_cube. 
The unit test was using the subroutine. So the test was updated to use the function.
Fixes #303

Remove duplicate 'to_upper' from chgres_cube

---

.github/workflows/esmf-8.0.1_jasper-2.0.22_nceplibs-1.3.0.yml
.github/workflows/esmf-8.0.1_jasper-2.0.22_nceplibs-develop.yml

The workflow uploads test-coverage.html and stores it as an artifact which can be manually  downloaded on the Actions page.
Also cache NCEPLIBS on this workflow by hashing the `VERSION` file contained in the repo.
See here for the current test coverage file: https://github.com/kgerheiser/UFS_UTILS/actions/runs/615240346

Report test coverage using gcovr

---

.github/workflows/esmf-8.0.1_jasper-2.0.22_nceplibs-1.3.0.yml
CMakeLists.txt
docs/CMakeLists.txt
docs/user_guide.md
sorc/chgres_cube.fd/CMakeLists.txt
sorc/chgres_cube.fd/atmosphere.F90
sorc/chgres_cube.fd/docs/CMakeLists.txt
sorc/chgres_cube.fd/docs/Doxyfile.in
sorc/chgres_cube.fd/docs/user_guide.md
sorc/chgres_cube.fd/input_data.F90

Part of #191 
Part of #357 
In this PR I separate out the doxygen build of chgres_cube from the rest of UFS_UTILS. Now the modules and data type sections of the documentation for chgres_cube look as we want them to.
The top level documentation now just contains a link to the chgres_cube documentation.
This will happen with all the other utilities as well, and then all the module and data type lists will look good.
One advantage of this approach is we can turn on WARN_AS_ERROR in the Doxyfile.in of each utility as we get the documentation completed. In the case of chgres_cube there were still two warnings, which I fix here, and I turn on WARN_AS_ERROR for chgres_cube.
@GeorgeGayno-NOAA I had to use one ??? for a missing field in input_data.F90. What should I put there?

separate chgres_cube doxygen build from rest of UFS_UTILS, fix remaining chgres_cube doxygen warnings, turn on WARN_AS_ERROR for chgres_cube

---

sorc/vcoord_gen.fd/docs/Doxyfile.in
sorc/vcoord_gen.fd/driver.f90
sorc/vcoord_gen.fd/matrix_utils.f90
sorc/vcoord_gen.fd/vcoord_gen.f90

Part of #191 
Fixes #403 
Clearing remaining doxygen warnings for vcoord_gen, and turning on WARN_AS_ERROR for doxygen there.

cleared doxygen warnings from vcoord_gen utility

---

sorc/global_cycle.fd/sfcsub.F

Eliminate remaining doxygen warnings from sfcsub.F.
Part of #191 
Fixes #398

Eliminate doxygen warnings from sfcsub.F of global_cycle

---

sorc/chgres_cube.fd/input_data.F90
sorc/chgres_cube.fd/model_grid.F90
sorc/chgres_cube.fd/surface.F90

Update a write statement that was causing a compile warning in the CI.
Remove some unused variables that can cause a warning
with some compilers.
Fixes #450

Eliminate compiler warning in chgres_cube

---

modulefiles/build.wcoss_cray.intel

Variable was removed by accident
Fixes #475

Re-add NETCDF env variable so CMake can find NetCDF on WCOSS Cray

---

sorc/orog_mask_tools.fd/orog.fd/mtnlm7_oclsm.f

When adapting the develop branch of the ufs-srweather-app to the MACOS platform, I found that the orog program would consistently exhibit segmentation faults for unknown reasons with my compiler (GNU 9.4.0 homebrew). We have seen this before for certain older fortran programs using GNU compilers when declaring variables as a size of a variable value in certain instances (e.g. #245). I was able to determine this was occurring during the variable declaration/allocation step in the "TERSUB" subroutine.
Given the impressively discombobulated state of that code, I decided it was best to reorganize the variable declaration section, change all variable-sized declared arrays to allocatable arrays, and allocate/deallocate those arrays as needed. This fixed the segmentation fault issue for MACOS, …

Clean up "orog" program (mtnlm7_oclsm.f) to eliminate segmentation faults on MACOS

---

cmake/LibMPI.cmake
fix/link_fixdirs.sh
modulefiles/build.s4.intel
sorc/machine-setup.sh
util/gdas_init/driver.s4.sh

Support for S4 has been added to the build scripts to support the global workflow.  Additionally, a partial driver for gdas_init (chgres only) has been written for S4.  The port is supported by an official build of hpc-stack supported by me on the system.  I have run several test cycles, the logs of which are available on Orion (/work/noaa/nesdis-rdo2/dhuber/s4_logs/test_dev).  I've also run a test case of gdas_init for 2019111818 @192/96, comparing the resulting outputs from S4 and Hera, which were bitwise identical.  Please let me know if you need any further tests completed.
Fixes #543

Port the build and gdas_init scripts to S4
